name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.10.5
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'

      - name: Display Python version
        run: python --version

      - name: Install NASM
        uses: ilammy/setup-nasm@v1

      - name: Display NASM version
        run: nasm --version

      - name: Checkout Branch to VM
        uses: actions/checkout@v3

      - name: Run Testing Framework
        run: ./test-nova.py --run tests
